window.NAME_STATS_DATA = {
  "source": "name_statistics_colored.xlsx",
  "chapters": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20
  ],
  "characters": [
    {
      "id": "第一代-何塞·阿尔卡蒂奥·布恩迪亚-2",
      "generation": "第一代",
      "name": "何塞·阿尔卡蒂奥·布恩迪亚",
      "counts": [
        38,
        29,
        41,
        23,
        10,
        6,
        7,
        0,
        3,
        3,
        3,
        2,
        4,
        1,
        1,
        2,
        3,
        0,
        0,
        1
      ],
      "total": 177,
      "gender": "男",
      "maleCount": 177,
      "femaleCount": 0,
      "peakChapter": 3,
      "peakValue": 41,
      "firstChapter": 1,
      "lastChapter": 20
    },
    {
      "id": "第一代-乌尔苏拉-3",
      "generation": "第一代",
      "name": "乌尔苏拉",
      "counts": [
        25,
        34,
        29,
        25,
        21,
        26,
        40,
        34,
        24,
        36,
        19,
        15,
        30,
        13,
        7,
        16,
        24,
        11,
        3,
        4
      ],
      "total": 436,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 436,
      "peakChapter": 7,
      "peakValue": 40,
      "firstChapter": 1,
      "lastChapter": 20
    },
    {
      "id": "第二代-何塞·阿尔卡蒂奥-4",
      "generation": "第二代",
      "name": "何塞·阿尔卡蒂奥",
      "counts": [
        3,
        24,
        4,
        0,
        14,
        10,
        11,
        4,
        1,
        1,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "total": 74,
      "gender": "男",
      "maleCount": 74,
      "femaleCount": 0,
      "peakChapter": 2,
      "peakValue": 24,
      "firstChapter": 1,
      "lastChapter": 13
    },
    {
      "id": "第二代-奥雷里亚诺·布恩迪亚-5",
      "generation": "第二代",
      "name": "奥雷里亚诺·布恩迪亚",
      "counts": [
        8,
        10,
        23,
        40,
        41,
        15,
        39,
        37,
        53,
        12,
        11,
        17,
        11,
        5,
        9,
        8,
        5,
        4,
        6,
        4
      ],
      "total": 358,
      "gender": "男",
      "maleCount": 358,
      "femaleCount": 0,
      "peakChapter": 9,
      "peakValue": 53,
      "firstChapter": 1,
      "lastChapter": 20
    },
    {
      "id": "第二代-蕾梅黛丝-6",
      "generation": "第二代",
      "name": "蕾梅黛丝",
      "counts": [
        0,
        0,
        2,
        21,
        12,
        3,
        4,
        1,
        3,
        1,
        4,
        1,
        3,
        0,
        0,
        0,
        1,
        0,
        2,
        0
      ],
      "total": 58,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 58,
      "peakChapter": 4,
      "peakValue": 21,
      "firstChapter": 3,
      "lastChapter": 19
    },
    {
      "id": "第二代-庇拉尔·特尔内拉-7",
      "generation": "第二代",
      "name": "庇拉尔·特尔内拉",
      "counts": [
        0,
        8,
        3,
        14,
        1,
        6,
        2,
        6,
        2,
        2,
        0,
        0,
        3,
        4,
        0,
        1,
        2,
        0,
        4,
        4
      ],
      "total": 62,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 62,
      "peakChapter": 4,
      "peakValue": 14,
      "firstChapter": 2,
      "lastChapter": 20
    },
    {
      "id": "第二代-阿玛兰妲-8",
      "generation": "第二代",
      "name": "阿玛兰妲",
      "counts": [
        0,
        5,
        7,
        20,
        21,
        20,
        17,
        25,
        12,
        7,
        8,
        10,
        23,
        31,
        0,
        3,
        1,
        7,
        1,
        2
      ],
      "total": 220,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 220,
      "peakChapter": 14,
      "peakValue": 31,
      "firstChapter": 2,
      "lastChapter": 20
    },
    {
      "id": "第二代-丽贝卡-9",
      "generation": "第二代",
      "name": "丽贝卡",
      "counts": [
        0,
        0,
        15,
        30,
        36,
        12,
        10,
        2,
        1,
        0,
        8,
        0,
        5,
        12,
        0,
        0,
        1,
        0,
        0,
        1
      ],
      "total": 133,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 133,
      "peakChapter": 5,
      "peakValue": 36,
      "firstChapter": 3,
      "lastChapter": 20
    },
    {
      "id": "第三代-阿尔卡蒂奥-10",
      "generation": "第三代",
      "name": "阿尔卡蒂奥",
      "counts": [
        0,
        0,
        6,
        11,
        8,
        52,
        4,
        2,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        0,
        0,
        1
      ],
      "total": 87,
      "gender": "男",
      "maleCount": 87,
      "femaleCount": 0,
      "peakChapter": 6,
      "peakValue": 52,
      "firstChapter": 3,
      "lastChapter": 20
    },
    {
      "id": "第三代-奥雷里亚诺·何塞-11",
      "generation": "第三代",
      "name": "奥雷里亚诺·何塞",
      "counts": [
        0,
        0,
        0,
        0,
        2,
        1,
        6,
        25,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0,
        2,
        0,
        0
      ],
      "total": 38,
      "gender": "男",
      "maleCount": 38,
      "femaleCount": 0,
      "peakChapter": 8,
      "peakValue": 25,
      "firstChapter": 5,
      "lastChapter": 18
    },
    {
      "id": "第三代-桑塔索菲亚·德拉·彼达-12",
      "generation": "第三代",
      "name": "桑塔索菲亚·德拉·彼达",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        4,
        1,
        2,
        2,
        4,
        1,
        1,
        5,
        1,
        11,
        4,
        8,
        10,
        0,
        1
      ],
      "total": 55,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 55,
      "peakChapter": 15,
      "peakValue": 11,
      "firstChapter": 6,
      "lastChapter": 20
    },
    {
      "id": "第三代-十七个奥雷里亚诺-13",
      "generation": "第三代",
      "name": "十七个奥雷里亚诺",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        20,
        14,
        1,
        3,
        0,
        0,
        0,
        2,
        0,
        0
      ],
      "total": 40,
      "gender": "男",
      "maleCount": 40,
      "femaleCount": 0,
      "peakChapter": 11,
      "peakValue": 20,
      "firstChapter": 11,
      "lastChapter": 18
    },
    {
      "id": "第四代-何塞·阿尔卡蒂奥第二-14",
      "generation": "第四代",
      "name": "何塞·阿尔卡蒂奥第二",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        21,
        2,
        0,
        6,
        0,
        35,
        2,
        13,
        1,
        0,
        0
      ],
      "total": 83,
      "gender": "男",
      "maleCount": 83,
      "femaleCount": 0,
      "peakChapter": 15,
      "peakValue": 35,
      "firstChapter": 7,
      "lastChapter": 18
    },
    {
      "id": "第四代-奥雷里亚诺第二-15",
      "generation": "第四代",
      "name": "奥雷里亚诺第二",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        41,
        25,
        7,
        24,
        27,
        16,
        36,
        28,
        5,
        0,
        1
      ],
      "total": 212,
      "gender": "男",
      "maleCount": 212,
      "femaleCount": 0,
      "peakChapter": 10,
      "peakValue": 41,
      "firstChapter": 7,
      "lastChapter": 20
    },
    {
      "id": "第四代-美人儿蕾梅黛丝-16",
      "generation": "第四代",
      "name": "美人儿蕾梅黛丝",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        6,
        14,
        2,
        24,
        1,
        2,
        0,
        0,
        1,
        2,
        1,
        1
      ],
      "total": 56,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 56,
      "peakChapter": 12,
      "peakValue": 24,
      "firstChapter": 8,
      "lastChapter": 20
    },
    {
      "id": "第四代-费尔南达-17",
      "generation": "第四代",
      "name": "费尔南达",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        31,
        9,
        23,
        40,
        28,
        24,
        27,
        23,
        5,
        7
      ],
      "total": 221,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 221,
      "peakChapter": 14,
      "peakValue": 40,
      "firstChapter": 10,
      "lastChapter": 20
    },
    {
      "id": "第四代-佩特拉·科特斯-18",
      "generation": "第四代",
      "name": "佩特拉·科特斯",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        13,
        9,
        1,
        9,
        9,
        1,
        12,
        14,
        2,
        0,
        1
      ],
      "total": 71,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 71,
      "peakChapter": 17,
      "peakValue": 14,
      "firstChapter": 10,
      "lastChapter": 20
    },
    {
      "id": "第五代-何塞·阿尔卡蒂奥-19",
      "generation": "第五代",
      "name": "何塞·阿尔卡蒂奥",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        11,
        2,
        1,
        1,
        2,
        31,
        2,
        0
      ],
      "total": 52,
      "gender": "男",
      "maleCount": 52,
      "femaleCount": 0,
      "peakChapter": 18,
      "peakValue": 31,
      "firstChapter": 11,
      "lastChapter": 19
    },
    {
      "id": "第五代-梅梅-20",
      "generation": "第五代",
      "name": "梅梅",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        8,
        79,
        16,
        3,
        2,
        2,
        0,
        0
      ],
      "total": 112,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 112,
      "peakChapter": 14,
      "peakValue": 79,
      "firstChapter": 11,
      "lastChapter": 18
    },
    {
      "id": "第五代-马乌里肖·巴比伦-21",
      "generation": "第五代",
      "name": "马乌里肖·巴比伦",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        21,
        7,
        0,
        0,
        0,
        0,
        0
      ],
      "total": 28,
      "gender": "男",
      "maleCount": 28,
      "femaleCount": 0,
      "peakChapter": 14,
      "peakValue": 21,
      "firstChapter": 14,
      "lastChapter": 15
    },
    {
      "id": "第五代-阿玛兰妲·乌尔苏拉-22",
      "generation": "第五代",
      "name": "阿玛兰妲·乌尔苏拉",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        4,
        2,
        3,
        15,
        5,
        26,
        30
      ],
      "total": 85,
      "gender": "女",
      "maleCount": 0,
      "femaleCount": 85,
      "peakChapter": 20,
      "peakValue": 30,
      "firstChapter": 14,
      "lastChapter": 20
    },
    {
      "id": "第五代-加斯通-23",
      "generation": "第五代",
      "name": "加斯通",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        25,
        6
      ],
      "total": 31,
      "gender": "男",
      "maleCount": 31,
      "femaleCount": 0,
      "peakChapter": 19,
      "peakValue": 25,
      "firstChapter": 19,
      "lastChapter": 20
    },
    {
      "id": "第六代-奥雷里亚诺·巴比伦-24",
      "generation": "第六代",
      "name": "奥雷里亚诺·巴比伦",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        3,
        14,
        45,
        47,
        49
      ],
      "total": 159,
      "gender": "男",
      "maleCount": 159,
      "femaleCount": 0,
      "peakChapter": 20,
      "peakValue": 49,
      "firstChapter": 15,
      "lastChapter": 20
    },
    {
      "id": "第七代-奥雷里亚诺-25",
      "generation": "第七代",
      "name": "奥雷里亚诺",
      "counts": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1
      ],
      "total": 1,
      "gender": "男",
      "maleCount": 1,
      "femaleCount": 0,
      "peakChapter": 20,
      "peakValue": 1,
      "firstChapter": 20,
      "lastChapter": 20
    }
  ]
};
